/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColumnResponse
 */
export interface ColumnResponse {
    /**
     * カラムID
     * @type {string}
     * @memberof ColumnResponse
     */
    id: string;
    /**
     * カラム名
     * @type {string}
     * @memberof ColumnResponse
     */
    name: string;
}

export function ColumnResponseFromJSON(json: any): ColumnResponse {
    return ColumnResponseFromJSONTyped(json, false);
}

export function ColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ColumnResponseToJSON(value?: ColumnResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


