/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentResponse
     */
    createDateTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommentResponse
     */
    updateDateTime: Date;
}

export function CommentResponseFromJSON(json: any): CommentResponse {
    return CommentResponseFromJSONTyped(json, false);
}

export function CommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
        'createDateTime': (new Date(json['createDateTime'])),
        'updateDateTime': (new Date(json['updateDateTime'])),
    };
}

export function CommentResponseToJSON(value?: CommentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'createDateTime': (value.createDateTime.toISOString()),
        'updateDateTime': (value.updateDateTime.toISOString()),
    };
}


