/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateColumnRequest
 */
export interface CreateColumnRequest {
    /**
     * カラム名
     * @type {string}
     * @memberof CreateColumnRequest
     */
    name: string;
}

export function CreateColumnRequestFromJSON(json: any): CreateColumnRequest {
    return CreateColumnRequestFromJSONTyped(json, false);
}

export function CreateColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateColumnRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateColumnRequestToJSON(value?: CreateColumnRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


