/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
    /**
     * タスク名
     * @type {string}
     * @memberof CreateTaskRequest
     */
    name: string;
    /**
     * タスクの説明
     * @type {string}
     * @memberof CreateTaskRequest
     */
    description: string;
    /**
     * 見積もり時間
     * @type {string}
     * @memberof CreateTaskRequest
     */
    estimatedTime: string;
    /**
     * プロジェクトのID
     * @type {string}
     * @memberof CreateTaskRequest
     */
    projectId: string;
    /**
     * ラベル一覧
     * @type {Array<string>}
     * @memberof CreateTaskRequest
     */
    labelIds: Array<string>;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'estimatedTime': json['estimatedTime'],
        'projectId': json['projectId'],
        'labelIds': json['labelIds'],
    };
}

export function CreateTaskRequestToJSON(value?: CreateTaskRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'estimatedTime': value.estimatedTime,
        'projectId': value.projectId,
        'labelIds': value.labelIds,
    };
}


