/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLabelRequest
 */
export interface CreateLabelRequest {
    /**
     * ラベル名
     * @type {string}
     * @memberof CreateLabelRequest
     */
    name: string;
    /**
     * ラベルの説明
     * @type {string}
     * @memberof CreateLabelRequest
     */
    description?: string;
    /**
     * @type {string}
     * @memberof CreateLabelRequest
     */
    color: string;
}

export function CreateLabelRequestFromJSON(json: any): CreateLabelRequest {
    return CreateLabelRequestFromJSONTyped(json, false);
}

export function CreateLabelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLabelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'projectId': json['projectId'],
    };
}

export function CreateLabelRequestToJSON(value?: CreateLabelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'projectId': value.projectId,
    };
}


