// tslint:disable
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LabelResponse
 */
export interface LabelResponse {
    /**
     * @type {string}
     * @memberof LabelResponse
     */
    id: string;
    /**
     * @type {string}
     * @memberof LabelResponse
     */
    name: string;
    /**
     * @type {string}
     * @memberof LabelResponse
     */
    description: string;
    /**
     * @type {string}
     * @memberof LabelResponse
     */
    color: string;
}
