/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ColumnResponse,
    ColumnResponseFromJSON,
    ColumnResponseFromJSONTyped,
    ColumnResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListColumnResponse
 */
export interface ListColumnResponse {
    /**
     * 
     * @type {Array<ColumnResponse>}
     * @memberof ListColumnResponse
     */
    columns?: Array<ColumnResponse>;
}

export function ListColumnResponseFromJSON(json: any): ListColumnResponse {
    return ListColumnResponseFromJSONTyped(json, false);
}

export function ListColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListColumnResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'columns': !exists(json, 'columns') ? undefined : ((json['columns'] as Array<any>).map(ColumnResponseFromJSON)),
    };
}

export function ListColumnResponseToJSON(value?: ListColumnResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'columns': value.columns === undefined ? undefined : ((value.columns as Array<any>).map(ColumnResponseToJSON)),
    };
}


