// tslint:disable
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string;
    /**
     * @type {string}
     * @memberof ProjectResponse
     */
    description: string;
    /**
     * @type {string}
     * @memberof ProjectResponse
     */
    createDateTime: string;
    /**
     * @type {string}
     * @memberof ProjectResponse
     */
    updateDateTime: string;
}
