/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuspendTimerResponse
 */
export interface SuspendTimerResponse {
    /**
     * 計測時間
     * @type {string}
     * @memberof SuspendTimerResponse
     */
    elapsedTime: string;
}

export function SuspendTimerResponseFromJSON(json: any): SuspendTimerResponse {
    return SuspendTimerResponseFromJSONTyped(json, false);
}

export function SuspendTimerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuspendTimerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elapsedTime': json['elapsedTime'],
    };
}

export function SuspendTimerResponseToJSON(value?: SuspendTimerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elapsedTime': value.elapsedTime,
    };
}


