// tslint:disable
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TaskResponse
 */
export interface TaskResponse {
    /**
     * タスク名
     * @type {string}
     * @memberof TaskResponse
     */
    name: string;
    /**
     * タスクの説明
     * @type {string}
     * @memberof TaskResponse
     */
    description: string;
    /**
     * プロジェクトのID
     * @type {string}
     * @memberof TaskResponse
     */
    projectId: string;
    /**
     * 見積もり時間
     * @type {string}
     * @memberof TaskResponse
     */
    estimatedTime: string;
    /**
     * 計測時間
     * @type {string}
     * @memberof TaskResponse
     */
    elapsedTime: string;
    /**
     * ラベル一覧
     * @type {Array<string>}
     * @memberof TaskResponse
     */
    labelIds: Array<string>;
}
