/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskResponse
 */
export interface TaskResponse {
    /**
     * タスク名
     * @type {string}
     * @memberof TaskResponse
     */
    name: string;
    /**
     * タスクの説明
     * @type {string}
     * @memberof TaskResponse
     */
    description: string;
    /**
     * プロジェクトのID
     * @type {string}
     * @memberof TaskResponse
     */
    projectId: string;
    /**
     * 見積もり時間
     * @type {string}
     * @memberof TaskResponse
     */
    estimatedTime: string;
    /**
     * 計測時間
     * @type {string}
     * @memberof TaskResponse
     */
    elapsedTime: string;
    /**
     * ラベル一覧
     * @type {Array<string>}
     * @memberof TaskResponse
     */
    labelIds: Array<string>;
    /**
     * カラムID
     * @type {string}
     * @memberof TaskResponse
     */
    columnId: string | null;
}

export function TaskResponseFromJSON(json: any): TaskResponse {
    return TaskResponseFromJSONTyped(json, false);
}

export function TaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'projectId': json['projectId'],
        'estimatedTime': json['estimatedTime'],
        'elapsedTime': json['elapsedTime'],
        'labelIds': json['labelIds'],
        'columnId': json['columnId'],
    };
}

export function TaskResponseToJSON(value?: TaskResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'projectId': value.projectId,
        'estimatedTime': value.estimatedTime,
        'elapsedTime': value.elapsedTime,
        'labelIds': value.labelIds,
        'columnId': value.columnId,
    };
}


