/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLabelRequest
 */
export interface UpdateLabelRequest {
    /**
     * ラベル名
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    name?: string;
    /**
     * ラベルの説明
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    description?: string;
    /**
     * ラベルの色(RGB形式)
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    color?: string;
}

export function UpdateLabelRequestFromJSON(json: any): UpdateLabelRequest {
    return UpdateLabelRequestFromJSONTyped(json, false);
}

export function UpdateLabelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLabelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'color': !exists(json, 'color') ? undefined : json['color'],
    };
}

export function UpdateLabelRequestToJSON(value?: UpdateLabelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'color': value.color,
    };
}


