// tslint:disable
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateLabelRequest
 */
export interface UpdateLabelRequest {
    /**
     * ラベル名
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    name: string;
    /**
     * ラベルの説明
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    description: string;
    /**
     * ラベルの色(RGB形式)
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    color: string;
    /**
     * プロジェクトのID
     * @type {string}
     * @memberof UpdateLabelRequest
     */
    projectId: string;
}
