// tslint:disable
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateTaskRequest
 */
export interface UpdateTaskRequest {
    /**
     * タスク名
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    name?: string;
    /**
     * タスクの説明
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    description?: string;
    /**
     * 見積もり時間
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    estimatedTime?: string;
    /**
     * ラベル一覧
     * @type {Array<string>}
     * @memberof UpdateTaskRequest
     */
    labelIds?: Array<string>;
}
