// tslint:disable
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateProjectRequest
 */
export interface UpdateProjectRequest {
    /**
     * プロジェクト名
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    name?: string;
    /**
     * プロジェクトの説明
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    description?: string;
}
