/* tslint:disable */
/* eslint-disable */
/**
 * DDD
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateColumnRequest
 */
export interface UpdateColumnRequest {
    /**
     * カラム名
     * @type {string}
     * @memberof UpdateColumnRequest
     */
    name: string;
}

export function UpdateColumnRequestFromJSON(json: any): UpdateColumnRequest {
    return UpdateColumnRequestFromJSONTyped(json, false);
}

export function UpdateColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateColumnRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateColumnRequestToJSON(value?: UpdateColumnRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


